---
- hosts: localhost

  tasks:

  - name: Install ClamAV basics
    apt: name=clamav state=latest

  - name: Install ClamAV scanner
    apt: name=clamav-scanner state=latest

  - name: Install ClamAV updater
    apt: name=clamav-update state=latest

  - copy:
      src: files/ansible.cron
      dest: /etc/cron.d/ansible.cron
      owner: root
      group: root
      mode: 0644

  - copy:
      src: files/ansible.freshclam
      dest: /etc/freshclam.conf
      owner: root
      group: root
      mode: 0644
